services:
  - type: web
    name: ecoquest-backend
    runtime: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
    image:
      url: ubuntu:22.04